# Generated by Django 3.0.3 on 2020-07-25 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
